### ISSUE TITLE
webp 파일 변환 방법 검토

### ISSUE THREAD

**Issue by mdgarden** [ZZIPSA/kkuk-kkuk-be#4]
---
name: Feature request
about: 아이디어 제안
title: "[Feature]"
labels: ''
assignees: ''

---

### 작업할 내용
유저가 프론트에 업로드한 .jpg, .png 파일 등을 webp로 변환하는 방법을 검토하고, 어느 파트에서 담당할지 결정합니다.

**Comment by 2chanhaeng** [comment]
[sharp](https://github.com/lovell/sharp) 사용하면 이미지 포맷 상관 없이 이렇게 해결할 수 있습니다. Next.js 서버 액션으로도 처리할 수 있구요.

```ts
import sharp from "sharp";

export const convertToWebp = async (image: File): Promise<Buffer> =>
  sharp(await image.arrayBuffer())
    .webp()
    .toBuffer();
```

**Comment by mdgarden** [comment]
해당 이슈는 Next.js로 통합 개발로 인해 클로즈합니다.
